GET http://localhost:3000

###
GET http://localhost:3000/routes

###
GET http://localhost:3000/routes/65d1d5725ae93f4c46939c75

###
POST http://localhost:3000/routes
Content-Type: application/json

{
  "name": "Rota Teste2",
  "source_id": "ChIJ2augpkFgz5QRuSrddO9MD4o",
  "destination_id": "ChIJOSerDab1xZQRGfRgtnrajzQ"
}

### MAPS

### GET place_id
GET http://localhost:3000/places?text=av itavuvu sorocaba

### GET directions between 2 locations
GET http://localhost:3000/directions?originId=ChIJ2augpkFgz5QRuSrddO9MD4o&destinationId=ChIJOSerDab1xZQRGfRgtnrajzQ